esphome:
  name: xiao-ir-mate
  friendly_name: XIAO Smart IR Mate
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:
  id: api_id
  encryption:   # Uses key set by Home Assistant
    actions:
    - action: send_ir_signal
      variables:
        protocol: string
        command: string # Used for NEC, Panasonic, LG, Sony, Samsung, JVC
        # Ideally the two following variables should be optional
        address: string
        nbits: int
      then:
        - if:
            condition:
              lambda: 'return protocol == "NEC";'
            then:
              - remote_transmitter.transmit_nec:
                  # Use a default address if none is provided
                  address: !lambda |-
                    if (address.empty()) return 0x7F80; 
                    return (uint16_t)strtoul(address.c_str(), nullptr, 16);
                  command: !lambda 'return (uint32_t)strtoul(command.c_str(), nullptr, 16);'
        - if:
            condition:
              lambda: 'return protocol == "LG";'
            then:
              - remote_transmitter.transmit_lg:
                  data: !lambda 'return (uint32_t)strtoul(command.c_str(), nullptr, 16);'
                  # Use 32 bits as a safe LG default if nbits is 0, other alternative is 28
                  nbits: !lambda 'return nbits == 0 ? 32 : nbits;'
        - if:
            condition:
              lambda: 'return protocol == "Sony";'
            then:
              - repeat:
                  count: 3 # Sony TVs require repeats
                  then:
                    - remote_transmitter.transmit_sony:
                        data: !lambda 'return (uint32_t)strtoul(command.c_str(), nullptr, 16);'
                        # Use 12 bits as a safe Sony default if nbits is 0
                        nbits: !lambda 'return nbits == 0 ? 12 : nbits;'
                    - delay: 45ms
        - if:
            condition:
              lambda: 'return protocol == "Samsung";'
            then:
              - remote_transmitter.transmit_samsung:
                  data: !lambda 'return (uint32_t)strtoul(command.c_str(), NULL, 16);'
        - if:
            condition:
              lambda: 'return protocol == "Panasonic";'
            then:
              - remote_transmitter.transmit_panasonic:
                  address: !lambda |-
                    // If address is empty, default to 0x4004 (most common Panasonic addr)
                    if (address.empty()) return 0x4004; 
                    return (uint16_t)strtoul(address.c_str(), nullptr, 16);
                  command: !lambda 'return (uint32_t)strtoul(command.c_str(), nullptr, 16);'
        - if:
            condition:
              lambda: 'return protocol == "Pioneer";'
            then:
              - repeat:
                  count: 3
                  then:
                    - remote_transmitter.transmit_pioneer:
                        rc_code_1: !lambda 'return (uint16_t)strtoul(command.c_str(), nullptr, 16);'
                    - delay: 40ms
        - if:
            condition:
              lambda: 'return protocol == "JVC";'
            then:
              - remote_transmitter.transmit_jvc:
                  data: !lambda 'return (uint32_t)strtoul(command.c_str(), NULL, 16);'
        - if:
            condition:
              lambda: 'return protocol == "Pronto";'
            then:
              - remote_transmitter.transmit_pronto:
                  data: !lambda 'return command;'
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

network:
  enable_ipv6: true

button:
  - platform: factory_reset
    id: factory_reset_button
    name: "Factory Reset"
    entity_category: diagnostic
    internal: true
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: config
    disabled_by_default: true
    icon: "mdi:restart"

remote_transmitter:
  id: ir_tx
  pin: GPIO3
  carrier_duty_percent: 50%

remote_receiver:
  - id: ir_rx
    pin:
      number: GPIO4
      inverted: true
    dump: all #we're not filtering out any protocols, IR Mate can handle it
    on_nec:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data:
              protocol: "NEC"
              address: !lambda 'return str_snprintf("%04X", 4, x.address);'
              command: !lambda 'return str_snprintf("%04X", 4, x.command);'
    on_lg:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data: {protocol: "LG", data: !lambda 'return x.data;'}
    on_panasonic:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data:
              protocol: "Panasonic"
              address: !lambda 'return str_snprintf("%04X", 4, x.address);'
              command: !lambda 'return str_snprintf("%08X", 8, x.command);'
    on_sony:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data: { protocol: "Sony", data: !lambda 'return str_snprintf("%08X", 8, x.data);' }
    on_samsung:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data: { protocol: "Samsung", data: !lambda 'return str_snprintf("%08X", 8, x.data);' }
    on_pioneer:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data: 
              protocol: "Pioneer"
              data: !lambda 'return str_snprintf("%08X", 8, x.rc_code_1);'
    on_jvc:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data: { protocol: "JVC", data: !lambda 'return str_snprintf("%04X", 4, x.data);' }
    on_pronto:
      then:
        - homeassistant.event:
            event: esphome.ir_code_received
            data:
              protocol: "Pronto"
              data: !lambda 'return x.data.c_str();'
# The codes can be listened to in config/developer-tools/event, the data can be used in trigggers as manual even received type: "esphome.ir_code_received"
# Data will depend on the protocol and code, protocols NEC and Panasonic will need data
# protocol: 
# address: 
# command: 
#
# other protocols, including pronot:
# protocol: 
# data: 
#
# Protocol can be omitted, but defining it in the trigger makes sure no codes overlap.
# Additionally, some remotes send the same signal a few times, preventing the automation from running more than once can be achieved with a "template" condition:
# {{ (now() | as_timestamp) - (state_attr('automation.your_automation_name', 'last_triggered') | as_timestamp | default(0)) > 1 }}

infrared:
  # IR transmitter instance
  - platform: ir_rf_proxy
    name: IR Proxy Transmitter
    id: ir_proxy_tx
    remote_transmitter_id: ir_tx
  # IR receiver instance
  - platform: ir_rf_proxy
    name: IR Proxy Receiver
    id: ir_proxy_rx
    remote_receiver_id: ir_rx

esp32_ble_tracker:
  id: ir_mate_ble_tracker

bluetooth_proxy:
  id: ir_mate_bt_proxy
  active: true

select:
  - platform: template
    name: Bluetooth Scanner Mode
    id: scanner_mode
    options:
      - "Passive"
      - "Active"
    lambda: |-
      if (id(ir_mate_ble_tracker).get_scan_active()) {
        return {"Active"};
      } else {
        return {"Passive"};
      }
    set_action:
      - lambda: |-
          id(ir_mate_bt_proxy).bluetooth_scanner_set_mode(x == "Active");
      - component.update: scanner_mode
