name: YAML lint

on:
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@cd7d140b5d224e94ca32e0fb3e2766efaddfc37c  # v5.0.0
      - name: Run yamllint
        run: yamllint --strict .
